//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by NinthStar.rc
//
#define IDC_MYICON                      2
#define IDD_NINTHSTAR_DIALOG            102
#define IDD_ABOUTBOX                    103
#define IDS_APP_TITLE                   103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDS_HELLO                       106
#define IDI_NINTHSTAR                   107
#define IDI_SMALL                       108
#define IDC_NINTHSTAR                   109
#define IDR_NES_ACCEL                   109
#define IDM_NES_MENU                    109
#define IDR_MAINFRAME                   128
#define IDD_PALETTE                     130
#define IDD_NES_PALETTE                 130
#define IDD_PATTERN                     131
#define IDD_NES_PATTERN                 131
#define IDD_NAME                        132
#define IDD_DUMPS                       134
#define IDD_NES_DUMPS                   134
#define IDD_TRACE                       135
#define IDD_NES_TRACE                   135
#define IDD_REGISTERS                   136
#define IDD_NES_REGISTERS               136
#define IDD_A26_DUMPS                   137
#define IDM_DEFMENU                     138
#define IDD_A26_REGISTERS               138
#define IDR_DEFACCEL                    139
#define IDD_A26_TRACE                   139
#define IDM_A26_MENU                    139
#define IDR_A26_ACCEL                   140
#define IDD_GEN_DUMPS                   140
#define IDM_GEN_MENU                    140
#define IDR_GEN_ACCEL                   141
#define IDD_GEN_REGISTERS               141
#define IDM_COL_MENU                    141
#define IDD_GEN_TRACE                   142
#define IDR_COL_ACCEL                   142
#define IDD_NES_CONTROLLERS             143
#define IDD_A26_CONTROLLERS             144
#define IDD_COL_TRACE                   145
#define IDD_COL_REGISTERS               146
#define IDD_COL_DUMPS                   147
#define IDD_COL_CONTROLLERS             148
#define IDC_DUMP_PPU_MEM                1002
#define IDC_START_LOGGING               1003
#define IDC_STOP_LOGGING                1004
#define IDC_IRQBUTTON                   1011
#define ID_CONTROLLERDIALOG_OK          1013
#define IDC_NES_CONTROLLERS_PLAYER_COMBO 1014
#define IDC_NES_CNT_A_DEVICE            1015
#define IDC_NES_CNT_A_KEY               1016
#define IDC_NES_CNT_B_DEVICE            1017
#define IDC_NES_CNT_SEL_DEVICE          1018
#define IDC_NES_CNT_STR_DEVICE          1019
#define IDC_NES_CNT_B_KEY               1020
#define IDC_NES_CNT_SEL_KEY             1021
#define IDC_NES_CNT_STR_KEY             1022
#define IDC_NES_CNT_AUTOCONFIGTO        1023
#define IDC_NES_CNT_AUTOCONFIGCOMBO     1024
#define IDC_COL_CONTROLLERS_PLAYER_COMBO 1025
#define IDC_A26_CNT_BUT_DEVICE          1026
#define IDC_A26_CNT_BUT_KEY             1027
#define IDC_A26_CNT_RIGHT_KEY           1028
#define IDC_A26_CNT_LEFT_KEY            1029
#define IDC_A26_CNT_DOWN_KEY            1030
#define IDC_NES_CNT_UP_DEVICE           1031
#define IDC_NES_CNT_UP_KEY              1032
#define IDC_NES_CNT_DOWN_DEVICE         1033
#define IDC_NES_CNT_LEFT_DEVICE         1034
#define IDC_NES_CNT_RIGHT_DEVICE        1035
#define IDC_NES_CNT_DOWN_KEY            1036
#define IDC_A26_CNT_UP_KEY              1036
#define IDC_NES_CNT_LEFT_KEY            1037
#define IDC_A26_CNT_RIGHT_DEVICE        1037
#define IDC_NES_CNT_RIGHT_KEY           1038
#define IDC_A26_CNT_LEFT_DEVICE         1038
#define IDC_A26_CNT_DOWN_DEVICE         1039
#define IDC_A26_CNT_UP_DEVICE           1040
#define IDC_A26_CNT_AUTOCONFIGCOMBO     1041
#define IDC_A26_CNT_AUTOCONFIGTO        1042
#define IDC_A26_CONTROLLERS_PLAYER_COMBO 1043
#define IDM_OPEN                        32772
#define ID_EMULATION_START              32773
#define ID_EMULATION_STOP               32774
#define ID_EMULATION_STEP               32775
#define ID_EMULATION_RESET              32776
#define ID_OPTIONS_DOUBLESIZEMODE       32777
#define ID_DEBUG_OFF                    32779
#define ID_DEBUG_LOW                    32780
#define ID_DEBUG_MEDIUM                 32781
#define ID_DEBUG_HIGH                   32782
#define ID_DEBUG_ULTRAHIGH              32783
#define ID_STATES_SAVESTATE             32784
#define ID_STATES_LOADSTATE             32785
#define ID_OPTIONS_CLEARALLBREAKPOINTS  32786
#define ID_OPTIONS_AUTOFRAMESKIP        32787
#define ID_OPTIONS_INCREASEFRAMESKIP    32788
#define ID_OPTIONS_DECREASEFRAMESKIP    32789
#define ID_OPTIONS_3DHARDWAREACCELERATION 32790
#define ID_OPTIONS_FILTERINGMODE_POINTNONE 32792
#define ID_OPTIONS_FILTERINGMODE_LINEAR 32793
#define ID_OPTIONS_FILTERINGMODE_CUBIC  32795
#define ID_OPTIONS_SOUNDOPTIONS         32796
#define ID_OPTIONS_SOUNDON              32797
#define ID_EMULATION_CPUMODE_NTSC       32798
#define ID_EMULATION_CPUMODE_PAL        32799
#define ID_OPTIONS_CONTROLLERCONFIG     32804
#define ID_EMULATION_PPUMODE_PIXELBASED 32805
#define ID_EMULATION_PPUMODE_SCANLINEBASED 32806
#define ID_EMULATION_PPUMODE_TILEBASED  32808
#define ID_OPTIONS_CONTROLLERMODE_PADDLES 32810
#define ID_OPTIONS_CONTROLLERMODE_JOYSTICKS 32811
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        145
#define _APS_NEXT_COMMAND_VALUE         32812
#define _APS_NEXT_CONTROL_VALUE         1044
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
